[versions]
publishdata = "1.4.0"
spotless = "8.0.0"
run = "3.0.2"
blossom = "2.1.0"

paper = "1.21.10-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
minecraft = "1.21.10"
brigadier = "1.4.0"

fabric-loader = "0.17.2"
fabric-loom = "1.11-SNAPSHOT"
fabric = "0.134.1+1.21.10"

neoforge-version = "21.10.43-beta"
neoforge-moddev = "2.0.116"

jspecify = "1.0.0"
jetbrains-annotations = "24.0.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
brigadier = { module = "net.strokkur:brigadier", version.ref = "brigadier" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }

# Modded
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric" }

[plugins]
publishdata = { id = "de.chojo.publishdata", version.ref = "publishdata" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run" }
run-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "run" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev"}

[bundles]
annotations = ["jspecify", "jetbrains-annotations"]
